# EmbedShaders.cmake — runs in script mode (cmake -P).
# Args: -DOUTPUT=<header path> -DFILES_DIR=<dir with .glsl/.vert/.frag>
# Generates a header with one inline constexpr char* per file.
# Variable name: filename without extension, camel-cased, prefixed with k
# (mesh_lit.vert -> kMeshLitVert).

if(NOT DEFINED OUTPUT OR NOT DEFINED FILES_DIR)
  message(FATAL_ERROR "EmbedShaders: OUTPUT and FILES_DIR are required")
endif()

file(GLOB FILE_LIST
  "${FILES_DIR}/*.glsl" "${FILES_DIR}/*.vert" "${FILES_DIR}/*.frag")
list(SORT FILE_LIST)

set(content "// Auto-generated by EmbedShaders.cmake — do not edit.\n#pragma once\n\n")

foreach(file IN LISTS FILE_LIST)
  get_filename_component(fname "${file}" NAME_WE)
  get_filename_component(fext "${file}" EXT)
  string(REGEX REPLACE "^\\." "" fext "${fext}")

  # camel-case the filename: mesh_lit -> MeshLit (CMake regex has no \U)
  string(REPLACE "_" ";" parts "${fname}")
  set(var "")
  foreach(part IN LISTS parts)
    string(SUBSTRING "${part}" 0 1 first)
    string(TOUPPER "${first}" first)
    string(SUBSTRING "${part}" 1 -1 rest)
    string(APPEND var "${first}${rest}")
  endforeach()
  string(SUBSTRING "${fext}" 0 1 fext_first)
  string(TOUPPER "${fext_first}" fext_first)
  string(SUBSTRING "${fext}" 1 -1 fext_rest)
  set(var "k${var}${fext_first}${fext_rest}")

  file(READ "${file}" src)
  string(APPEND content "inline constexpr const char* ${var} = R\"GLSL(\n${src})GLSL\";\n\n")
endforeach()

file(WRITE "${OUTPUT}" "${content}")
